{spawn} = require 'child_process'
fs = require 'fs'

run = (cmd) ->
  # Semi-hack: allow to call commands on local node_modules/.bin dir.
  cmd = "PATH=\"node_modules/.bin:$PATH\" #{cmd}"
  spawn 'bash', ['-c', cmd], stdio: 'inherit'

task 'watch:coffee', 'compile coffee source files everytime they change', ->
  run 'coffee --watch --compile -o lib src'

task 'watch:grammar', 'compile Jison grammar file everytime it changes', ->
  # Use Nodemon to watch grammar file and run Jison on every change.
  run 'nodemon -q -w src/grammar.jison -x jison src/grammar.jison -o lib/grammar.js'

task 'watch:test', 'run tests everytime source files or test files change', ->
  invoke 'watch:coffee'
  invoke 'watch:grammar'
  run 'mocha --watch --reporter min --growl'

task 'watch:index', 're-build merged index.js file everytime a source file changes', ->
  invoke 'watch:coffee'
  invoke 'watch:grammar'
  # Use Nodemon to watch lib directory and invoke build:index on every change.
  run 'nodemon -q -w lib/ -x cake build:index'

task 'build:index', 'build a merged script, index.js, to include in index.html', ->
  run 'cat <(echo "// Generated by Browserify") <(browserify lib/index.js) >assets/index.js'

task 'test', 'run tests', ->
  run 'mocha'