SHELL = /bin/bash

coffee_files = $(wildcard src/*.coffee)
js_files = $(coffee_files:src/%.coffee=lib/%.js) lib/grammar.js
bin_dir = node_modules/.bin
js_bundle = assets/index.js

all: build

lib/grammar.js: src/grammar.jison
	$(bin_dir)/jison -o $@ $<

lib/%.js: src/%.coffee
	$(bin_dir)/coffee -co lib $<

$(js_bundle): $(js_files)
	$(bin_dir)/browserify -o $@ lib/index.js
	@echo "// Generated by Browserify" | cat - $@ >$@.tmp && mv $@.tmp $@

.PHONY: build clean test watch

build: $(js_files) $(js_bundle)

clean:
	rm -rf lib $(js_bundle)

test: build
	$(bin_dir)/mocha --growl --colors >/dev/null

watch: test
	@inotifywait \
	  --monitor --quiet \
	  --event modify,close_write,moved_to,move_self,create,delete,delete_self \
	  --exclude ___jb_ \
	  --recursive src test | while read; do make test; done